version: '3.8'

services:
  db_postgres:
    image: postgres:15-alpine
    container_name: wikibot_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wikibot
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wikibot_network

  db_chroma:
    image: chromadb/chroma:latest
    container_name: wikibot_chromadb
    restart: always
    ports:
      - "8005:8000"
    environment:
      - ANONYMIZED_TELEMETRY=False
    volumes:
      - chroma_data:/chroma/data
    networks:
      - wikibot_network

  wikibot_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wikibot_backend
    restart: always
    environment:
      - ENVIRONMENT=production
      - OFFLINE_MODE=True
      - LOCAL_DB_TYPE=postgresql
      - DATABASE_URL=postgresql://postgres:postgres@db_postgres:5432/wikibot
      - CHROMA_TYPE=http
      - CHROMA_HOST=db_chroma
      - CHROMA_PORT=8000
      - JWT_SECRET_KEY=0bVV?R*M*_3+17GjWc1CYL^uf>-_1Av7D;02vjqqF1X?=W39R8op^%Ng=.a=+R~g
    ports:
      - "8080:8000"
    depends_on:
      - db_postgres
      - db_chroma
    networks:
      - wikibot_network

  wikibot_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wikibot_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3080:3000"
    depends_on:
      - wikibot_backend
    networks:
      - wikibot_network

volumes:
  postgres_data:
    driver: local
  chroma_data:
    driver: local

networks:
  wikibot_network:
    driver: bridge
