"""add_timeout_to_ai_provider_config

Revision ID: 3594d57ca436
Revises: f334b4d80974
Create Date: 2026-05-03 23:35:20.978798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3594d57ca436'
down_revision: Union[str, None] = 'f334b4d80974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column already exists to avoid duplicate column error
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('ai_provider_config')]
    
    if 'timeout' not in columns:
        # Add column as nullable first (SQLite limitation)
        op.add_column('ai_provider_config', sa.Column('timeout', sa.Integer(), nullable=True))
        # Update existing records to have default timeout
        op.execute("UPDATE ai_provider_config SET timeout = 30 WHERE timeout IS NULL")
    # SQLite doesn't support ALTER COLUMN to add NOT NULL constraint
    # The model will enforce the NOT NULL constraint for new records
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_provider_config', 'timeout')
    # ### end Alembic commands ###
